# Generated by Django 3.1.3 on 2020-11-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydoit',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mydoit',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
