# Generated by Django 3.1.3 on 2020-11-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydoit', '0002_auto_20201124_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydoit',
            old_name='added_date',
            new_name='added_on',
        ),
    ]
