# Generated by Django 3.1.3 on 2020-11-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydoit', '0003_auto_20201124_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydoit',
            name='updated_on',
        ),
    ]
