# Generated by Django 3.1.3 on 2020-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoit', '0004_remove_mydoit_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydoit',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
