# Generated by Django 3.1.3 on 2020-11-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydoit', '0005_mydoit_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydoit',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
